image: gitpod/workspace-full

tasks:
  - name: Install & run tests
    init: |
      npm ci
      npx playwright install --with-deps
    command: |
      eval "$(gp env -e)"
      npm run test:parallel

ports:
  - port: 9222
    onOpen: ignore